defmodule Tonflix.Repo.Migrations.CreateUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :hashed_password, :text
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :gender, :text, null: false
      add :honorific_title, :text
      add :street, :text, null: false
      add :zip_code, :text, null: false
      add :country, :text, null: false
      add :birthdate, :date, null: false
      add :mobile_phone_number, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:users)
  end
end
